# Computer Lab Exercises week 4

* These lab exercises give practice in using regular expressions.  https://www.w3schools.com/python/python_regex.asp
* A screencast on downloading jupyter notebooks from the online store.
https://youtu.be/1zY7hIj5tWg
* These exercises are **not** part of the assessment of the Module.
* I will post the solutions roughly 1 week after this file has been uploaded to the DLE.
* Please note that pasting python from pdf can sometimes cause problems. For example quotation marks can sometimes be converted incorrectly, so then running python will cause errors.

* See https://sites.google.com/view/pythonforstemstudents/home for a collection of links to information on python.


## Question 1a)

* Modify the script so that the search for the word **hot** is at the end of the string. 

In [3]:
import re
xxx =  "The mustard was very hot"

if re.search("cold", xxx) :
    print(xxx)


In [4]:
# Put your solution here

import re
xxx =  "The mustard was very hot"

if re.search("hot$", xxx) :
    print(xxx)



The mustard was very hot


## Question 1b)

* Create a regular expression that matches a credit card number of  1234-5678-9000-1101 
* The check should match for the **OK** numbers and fail for the **FAIL** numbers

The output should look like:
<pre>
The format is correct for  1234-5678-9000-1101
The format is correct for  1224-5172-9304-1121
1245 5619 2722 7890 is not a credit card number
121563921227241 is not a credit card number
</pre>


In [13]:
# Put your solution here
credit_numberA = "1234-5678-9000-1101"  # OK
credit_numberB = "1224-5172-9304-1121"  # OK

not_credit_numberA = "1245 5619 2722 7890" # FAIL
not_credit_numberB = "121563921227241" # FAIL


In [14]:
credit_numberA = "1234-5678-9000-1101"  # OK
credit_numberB = "1224-5172-9304-1121"  # OK

not_credit_numberA = "1245 5619 2722 7890" # FAIL
not_credit_numberB = "121563921227241" # FAIL


for xxx in [credit_numberA, credit_numberB, not_credit_numberA, not_credit_numberB] : 
  if re.search(r"\d\d\d\d-\d\d\d\d-\d\d\d\d-\d\d\d\d", xxx) :
    print("The format is correct for " , xxx)
  else:
    print(xxx, "is not a credit card number")


The format is correct for  1234-5678-9000-1101
The format is correct for  1224-5172-9304-1121
1245 5619 2722 7890 is not a credit card number
121563921227241 is not a credit card number


##  Question 2


This exercise is an example of using regular expressions to 
match parts of strings. The python code below prints 
out part of the wikipedia page for Devon.

I am asking you to use regular expressions
(see https://www.tutorialspoint.com/python/python_reg_expressions.htm
and the lecture notes) to find the line number, which match conditions.

* Q1 Print the line, which starts with **To**.
* Q2 Print the line, which ends with **hilly**.
* Q3 Select the line with numbers on it.
* Q4 Select the line with two and.

As an example I show Q0 which matches **granite**

In [88]:
import re

data = [ "The north and south coasts of Devon each have both cliffs and sandy shores." , 
    "The inland terrain is rural, and generally hilly.",
    "Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).",
    "Its moorland extends across a large expanse of granite bedrock.",
    "To the north of Dartmoor are the Culm Measures and Exmoor.",   
    "In the valleys and lowlands of south and east Devon the soil is more fertile."
 ] 

for count,xxx in enumerate(data) :
   print("line[", count, "]=",  xxx) 
   if re.search("granite", xxx)  :
       print("Answer to question 0 on line ", count)

line[ 0 ]= The north and south coasts of Devon each have both cliffs and sandy shores.
line[ 1 ]= The inland terrain is rural, and generally hilly.
line[ 2 ]= Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).
line[ 3 ]= Its moorland extends across a large expanse of granite bedrock.
Answer to question 0 on line  3
line[ 4 ]= To the north of Dartmoor are the Culm Measures and Exmoor.
line[ 5 ]= In the valleys and lowlands of south and east Devon the soil is more fertile.


In [94]:
import re

data = [ "The north and south coasts of Devon each have both cliffs and sandy shores." , 
    "The inland terrain is rural, and generally hilly.",
    "Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).",
    "Its moorland extends across a large expanse of granite bedrock.",
    "To the north of Dartmoor are the Culm Measures and Exmoor.",   
    "In the valleys and lowlands of south and east Devon the soil is more fertile."
 ] 

print("Answers ")
for count,xxx in enumerate(data) :
   print("line[", count, "]=",  xxx) 
   if re.search("granite", xxx)  :
       print("Answer to question 0 on line ", count)
   if re.search("^To", xxx)  :
       print("Answer to question 1 on line ", count)
   if re.search("hilly.$", xxx)  :
       print("Answer to question 2 on line ", count)
   if re.search("[0-9][0-9][0-9]" , xxx) :
       print("Answer to question 3 on line ", count)
   if re.search(r" and.*and" , xxx) :
       print("Answer to question 4 on line ", count)



Answers 
line[ 0 ]= The north and south coasts of Devon each have both cliffs and sandy shores.
Answer to question 4 on line  0
line[ 1 ]= The inland terrain is rural, and generally hilly.
Answer to question 2 on line  1
line[ 2 ]= Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).
Answer to question 3 on line  2
line[ 3 ]= Its moorland extends across a large expanse of granite bedrock.
Answer to question 0 on line  3
line[ 4 ]= To the north of Dartmoor are the Culm Measures and Exmoor.
Answer to question 1 on line  4
line[ 5 ]= In the valleys and lowlands of south and east Devon the soil is more fertile.
Answer to question 4 on line  5


The output from my code is:
<pre>
line[ 0 ]= The north and south coasts of Devon each have both cliffs and sandy shores.
Answer to question 4 on line  0
line[ 1 ]= The inland terrain is rural, and generally hilly.
Answer to question 2 on line  1
line[ 2 ]= Dartmoor is the largest open space in southern England, at 954 km2 (368 square miles).
Answer to question 3 on line  2
line[ 3 ]= Its moorland extends across a large expanse of granite bedrock.
line[ 4 ]= To the north of Dartmoor are the Culm Measures and Exmoor.
Answer to question 1 on line  4
line[ 5 ]= In the valleys and lowlands of south and east Devon the soil is more fertile.
Answer to question 4 on line  5
</pre>


I recommend you also explore using the wikipedia module
https://stackabuse.com/getting-started-with-pythons-wikipedia-api/
to download content from Wikipedia. This is NOT part of the exercise,
but it is the natural next step.

##  Question 3 (more regular expressions)
* The example below is a python script to extract email addresses from the string **input**
* Unfortunately the script only finds two emails
* Modify the script to extract all the emails.
* I would start by understanding the regular expression in **findall**

In [61]:
import re

input = """
My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com
"""
print("--------------------------------------------------")
print(input)
print("--------------------------------------------------")

# modify this line
tuples = re.findall(r'\b\w*\.\w*@\w*\.\w*.\w*\b' , input)

print("Extracted emails")
for tuple in tuples:
    print(tuple) 

--------------------------------------------------

My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com

--------------------------------------------------
Extracted emails
yyy.dong@plymouth.ac.uk
richard.gggg@plymouth.ac.uk


In [97]:
# Solution
import re

input = """
My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com
"""
print("--------------------------------------------------")
print(input)
print("--------------------------------------------------")

# modify this line
tuples = re.findall(r'\b[a-z\.]*@[a-z\.]*\b' , input)

print("Extracted emails")
for tuple in tuples:
    print(tuple) 

--------------------------------------------------

My main email is yyy.dong@plymouth.ac.uk
I have three other emails richard.gggg@plymouth.ac.uk , gggg@gmail.com
jjj@hotmail.com
My personal email is gig@yahoo.com

--------------------------------------------------
Extracted emails
yyy.dong@plymouth.ac.uk
richard.gggg@plymouth.ac.uk
gggg@gmail.com
jjj@hotmail.com
gig@yahoo.com


The goal is use regular expressions to extract all the email
addresses in a string variable.

This exercise is an example of using regular expressions to 
match parts of strings. The above python code extracts some
of the email addresses from the string **input**.
The regular expression matches emails of the form:
letters-or-numbers.letters-or-numberse@letters-or-numbers.letters-or-numbers.letters-or-numbers .
The command "\b" matches the spacing between words.

The current python code does not extract all the email addresses, so
the task is to modify the regular expression so that the python
extracts all the email addresses. See
https://www.tutorialspoint.com/python/python_reg_expressions.htm
and the lecture notes.



## Question  4  (Harder)
*  The csv file resources_69441989-dac6-4a8e-92e3-6d1dbe93fd2b_devon-businesses.csv contains information about Devon companies. The file is available on the DLE.
*  The data set is from  https://plymouth.thedata.place/dataset/devon-businesses 

The exercise is to check the post codes in the csv file. For example the enteries in column **RegAddress.PostCode**  and column **Pcodelookup**. 

* Modify the code below so that the **CompanyNumber** number is printed out if the **RegAddress.PostCode** and **Pcodelookup** are different (after removing any spaces). 

* Also print out the **CompanyNumber** when the postcode is not in the correct format. https://ideal-postcodes.co.uk/guides/uk-postcode-format To simplify the problem just assume that the postcode is a combination of letters and numbers.


Just for information you can look up information about companies using  https://find-and-update.company-information.service.gov.uk/?_ga=2.26241021.174329778.1666023410-664048164.1666023410

In [16]:
import csv
import re
name = "resources_69441989-dac6-4a8e-92e3-6d1dbe93fd2b_devon-businesses.csv"
print("Readng the data from " , name)

store = []
with open(name,encoding="ISO-8859-1") as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    next(readCSV) 
    for row in readCSV:

                    company_no     = row[0]
                    postcode       = row[6].replace(" ","")
                    postcode_regen = row[18].replace(" ","")

                    if not re.search("\D", postcode) :
                       print("Problem " , postcode, company_no )
                       store.append(company_no)
        
                    if postcode != postcode_regen :
                         print(company_no, postcode, postcode_regen)
                         

print("---------------")

print("Incorrect postcode")
store.sort()
for ss in store :
    print(ss)


Readng the data from  resources_69441989-dac6-4a8e-92e3-6d1dbe93fd2b_devon-businesses.csv
7184783 TQ139AE TQ129TH Other retail sale not in stores, stalls or markets
4885342 TQ139AE TQ129TH Other retail sale not in stores, stalls or markets
4679804 EX141LA EX139AG Temporary employment agency activities
7827975 TQ139AE TQ129TH Other retail sale not in stores, stalls or markets
5406775 TQ148NH TQ139YZ Information technology consultancy activities
7562642 EX348EW EX332ZQ Management consultancy activities other than financial management
4713405 TQ141BD TQ139YZ Painting
7191932 EX201AS EX29ZS Renting and leasing of other machinery, equipment and tangible goods n.e.c.
8954253 TQ110BQ TQ109YT Other business support service activities n.e.c.
1447828 EX172AJ EX169WZ Residents property management
8047454 TQ121QH TQ110YJ specialised design activities
8516808 EX349PJ EX332ZQ Environmental consulting activities
7240704 EX173LQ EX169WZ Other service activities n.e.c.
7576855 EX392AT EX389AP Managemen

6958247 EX311PQ EX39AS Artistic creation
7690642 TQ149JQ TQ139YZ Other professional, scientific and technical activities n.e.c.
7743891 PL210DB PL207UZ Retail sale in commercial art galleries
9130225 EX392AR EX389AP Architectural activities
5879388 EX348AL EX332ZQ Residents property management
5875783 TQ122HP TQ110YJ Other amusement and recreation activities n.e.c.
8153415 EX172AJ EX169WZ Other food services
7433291 PL210DB PL207UZ Other human health activities
9140012 EX111DT EX109YN Other service activities n.e.c.
8238731 EX111TG EX109YN Information technology consultancy activities
5590773 EX142YS EX139AG Management of real estate on a fee or contract basis
8188472 EX332EA EX329PH Dormant Company
8849480 EX327DD EX314ZQ Dormant Company
5546316 EX311HG EX39AS Distilling, rectifying and blending of spirits
7577544 EX173LQ EX169WZ Plumbing, heat and air-conditioning installation
7716054 EX166AA EX159AX Scaffold erection
4747042 TQ139AE TQ129TH Floor and wall covering
8332169 TQ122HP TQ

9479649 EX109BJ EX19WN plied
9972506 EX151UG EX149YS plied
9729737 EX393DN EX389AP plied
9840600 EX226DL EX215ZG plied
9746218 PL219JQ PL207UZ plied
9935477 EX363BQ EX356WY plied
9975472 TQ149AF TQ139YZ plied
9676572 EX166QP EX159AX plied
9477116 EX135PX EX129AP plied
9911474 EX166NL EX159AX plied
9587941 EX201HQ EX29ZS plied
9379903 EX151LB EX149YS plied
9472789 EX151LB EX149YS plied
9912516 EX109UB EX19WN plied
9610608 PL210UB PL207UZ plied
9918675 EX111HH EX109YN plied
9917325 TQ148DP TQ139YZ plied
9500546 EX165JS EX159AX plied
9400871 TQ122SN TQ110YJ plied
9586465 TQ121PN TQ110YJ plied
9827426 TQ122ER TQ110YJ plied
9438130 EX111AB EX109YN plied
9614917 EX151LB EX149YS plied
9933723 EX349PN EX332ZQ plied
9822788 EX311HR EX39AS plied
9473329 EX393NR EX389AP plied
9810329 TQ13BJ TQ139YZ plied
9821892 EX111HU EX109YN plied
9596191 TQ121EF TQ110YJ plied
9965275 EX166NL EX159AX plied
9398861 EX201AS EX29ZS plied
9342493 EX166PE EX159AX plied
9512077 EX393SH EX389AP plied
9738947 EX393DQ 

5914987 EX172AJ EX169WZ Plumbing, heat and air-conditioning installation
5850322 EX166AH EX159AX Real estate agencies
763194 TQ122JS TQ110YJ Growing of cereals (except rice), leguminous crops and oil seeds
4907886 TQ122JS TQ110YJ Other manufacturing n.e.c.
5633837 TQ130DA TQ129TH Other sports activities
7620373 EX122NY EX111ZU Electrical installation
7656061 EX173LB EX169WZ Furnace and chimney cleaning services
7582738 EX111AR EX109YN Tax consultancy
7363177 EX311TZ EX39AS Other service activities n.e.c.
8678013 EX166NL EX159AX Performing arts
5878050 EX348HN EX332ZQ Other specialist photography
7789055 EX171DW EX169WZ Sea and coastal freight water transport
8705637 EX172EL EX169WZ Private security activities
8580023 EX311PJ EX39AS Other service activities n.e.c.
5885151 EX392JJ EX389AP Other service activities n.e.c.
8032358 TQ130LT TQ129TH Construction of domestic buildings
7686936 TQ148DZ TQ139YZ Management consultancy activities other than financial management
Problem   6938846
693

8807776 EX109HB EX19WN Activities of sport clubs
1832050 TQ149HJ TQ139YZ Residents property management
OC382897 TQ122JS TQ110YJ plied
8738901 TQ149EL TQ139YZ Other social work activities without accommodation n.e.c.
OC369342 EX388EZ EX379ZN plied
OC359846 TQ122JS TQ110YJ plied
8296427 EX166AL EX159AX Management of real estate on a fee or contract basis
1534708 EX122PF EX111ZU Other social work activities without accommodation n.e.c.
7709431 PL219HZ PL207UZ Growing of vegetables and melons, roots and tubers
8263483 EX108BP EX19WN Botanical and zoological gardens and nature reserves activities
8805950 TQ122JS TQ110YJ Dormant Company
OC362080 EX328HR EX314ZQ plied
7538499 EX166PU EX159AX Other human health activities
8617312 EX109EZ EX19WN Educational support services
7244341 PL219FF PL207UZ Management of real estate on a fee or contract basis
8444243 EX173LQ EX169WZ Residents property management
9413144 TQ122HR TQ110YJ plied
9138624 TQ121GG TQ110YJ Activities of professional membership o

OC363912 EX363LH EX356WY plied
7141194 PL199FA PL189TG Activities of head offices
5065966 EX313TD EX39AS Dormant Company
5101167 EX143UN EX139AG Activities of religious organizations
5861223 EX363LH EX356WY Raising of horses and other equines
2431675 TQ124AA TQ110YJ Residents property management
3048646 EX108LS EX19WN Other education n.e.c.
5717476 PL210UT PL207UZ Residents property management
3741462 EX364AS EX356WY Other education n.e.c.
3707566 EX166NH EX159AX Other social work activities without accommodation n.e.c.
4738406 EX166NB EX159AX Other passenger land transport
OC363508 EX311QN EX39AS plied
6366140 TQ125FB TQ110YJ Activities of other membership organizations n.e.c.
5435242 PL210UT PL207UZ Residents property management
4171822 EX173LF EX169WZ Support activities to performing arts
6891935 TQ124XX TQ110YJ Activities of other membership organizations n.e.c.
OC383562 TQ126RG TQ110YJ plied
2349891 PL219NU PL207UZ Non-trading company
1391702 EX108LD EX19WN Residents property mana

9533053 EX151RQ EX149YS plied
9633819 TQ139PU TQ129TH plied
9629070 TQ130LZ TQ129TH plied
9874892 EX388BY EX379ZN plied
9524808 TQ122DT TQ110YJ plied
9791994 TQ125NP TQ110YJ plied
9792051 TQ125NP TQ110YJ plied
9569689 TQ124LF TQ110YJ plied
9790794 EX169JA EX159AX plied
9617075 EX149JY EX139AG plied
9548290 EX168PD EX159AX plied
9800683 EX153SG EX149YS plied
9765536 EX151SB EX149YS plied
9533374 TQ123SF TQ110YJ plied
9866704 EX314AY EX39AS plied
9774661 TQ126RY TQ110YJ plied
9516647 EX135PH EX129AP plied
9860418 EX168BL EX159AX plied
9766914 EX331FD EX329PH plied
9632355 EX151BQ EX149YS plied
9880496 TQ126UH TQ110YJ plied
9635649 TQ126BQ TQ110YJ plied
9891364 EX227LP EX215ZG plied
9621623 TQ124AD TQ110YJ plied
9802103 TQ109AW TQ19SU plied
9801345 EX151BS EX149YS plied
9801317 EX151BS EX149YS plied
9801316 EX151BS EX149YS plied
9492988 TQ124RD TQ110YJ plied
9542974 TQ139SX TQ129TH plied
9327446 EX331AA EX329PH plied
9621735 EX169NG EX159AX plied
9784763 EX152SH EX149YS plied
9864507 EX39

9331749 EX313TD EX39AS Other sports activities
9207516 EX141DE EX139AG Other accommodation
9297246 TQ123DS TQ110YJ Unlicensed carrier
9088486 EX167NJ EX159AX Hunting, trapping and related service activities
9197725 PL207HF PL29BF Repair and maintenance of other transport equipment n.e.c.
9234024 TQ110LL TQ109YT Electrical installation
9053188 TQ124AA TQ110YJ Dormant Company
8762684 EX201DP EX29ZS Agents involved in the sale of machinery, industrial equipment, ships and aircraft
9214120 TQ122QA TQ110YJ Other specialised construction activities n.e.c.
9105773 EX135AD EX129AP Unlicensed carrier
9238489 EX173AH EX169WZ Other reservation service activities n.e.c.
9668708 EX173AH EX169WZ Manufacture of other furniture
9219468 EX349LL EX332ZQ Agents involved in the sale of a variety of goods
9326422 EX204NS EX29ZS Other service activities n.e.c.
9229854 TQ148EB TQ139YZ Development of building projects
9198992 EX198EH EX187YU Dormant Company
9240233 TQ110LL TQ109YT Private security activities


3781123 PL210XQ PL207UZ Other professional, scientific and technical activities n.e.c.
8691761 EX153PL EX149YS Temporary employment agency activities
6697181 EX151AE EX149YS Agents involved in the sale of a variety of goods
7373068 EX364NH EX356WY Other business support service activities n.e.c.
4634658 EX173AH EX169WZ Mixed farming
5003004 EX347DJ EX332ZQ Residents property management
7014505 EX111XH EX109YN Management consultancy activities other than financial management
5936556 EX215BS EX209AL Mixed farming
7141183 EX173AH EX169WZ Raising of poultry
5229119 TQ124PB TQ110YJ Non-specialised wholesale trade
4887428 EX135RJ EX129AP Advertising agencies
4540087 TQ139XP TQ129TH Other specialised construction activities n.e.c.
6299218 TQ138NX TQ129TH Advertising agencies
3699833 TQ124AA TQ110YJ Other business support service activities n.e.c.
8280760 TQ124AA TQ110YJ Other business support service activities n.e.c.
7789703 TQ137HS TQ129TH Operation of arts facilities
4886141 EX135AD EX129A

2762906 TQ124SG TQ110YJ Dormant Company
4763305 EX148SE EX139AG Retail sale of sports goods, fishing gear, camping goods, boats and bicycles
8252438 EX143DQ EX139AG Other retail sale of food in specialised stores
8270006 EX122AD EX111ZU Hairdressing and other beauty treatment
8549268 EX137BX EX129AP Development of building projects
4946383 TQ122QA TQ110YJ Other service activities n.e.c.
9187399 EX149SY EX139AG Manufacture of wine from grape
Problem   1520456
1520456  #N/A Water collection, treatment and supply
985963 EX392AY EX389AP Residents property management
8826899 EX168DU EX159AX Construction of domestic buildings
5551339 EX164AL EX159AX Licensed clubs
7588557 EX175PW EX169WZ Management consultancy activities other than financial management
8624620 TQ122QA TQ110YJ Financial intermediation not elsewhere classified
6683178 PL210QR PL207UZ Manufacture of kitchen furniture
7757413 TQ149HZ TQ139YZ Educational support services
7195534 EX396HB EX389AP Environmental consulting activities

2134755 EX175PP EX169WZ Other letting and operating of own or leased real estate
4002051 TQ148BL TQ139YZ Management consultancy activities other than financial management
5432065 TQ124PB TQ110YJ Other building completion and finishing
7449760 EX168BH EX159AX Business and domestic software development
6133108 EX152HJ EX149YS Electrical installation
7667529 EX227PA EX215ZG Other service activities n.e.c.
5062528 EX173LQ EX169WZ Electrical installation
4446484 TQ122QA TQ110YJ Printing n.e.c.
7635581 EX226DY EX215ZG Retail trade of motor vehicle parts and accessories
2821988 EX100JA EX19WN Other letting and operating of own or leased real estate
8070053 EX123BL EX111ZU Other retail sale not in stores, stalls or markets
6590688 EX137HW EX129AP Agents selling agricultural raw materials, livestock, textile raw materials and semi-finished goods
4771009 TQ126TQ TQ110YJ specialised design activities
7604627 EX203QB EX29ZS Other business support service activities n.e.c.
8527904 PL210LL PL207UZ O

4930674 EX328HR EX314ZQ Development of building projects
5454354 EX100QR EX19WN Other specialised construction activities n.e.c.
7048947 EX311PJ EX39AS Other building completion and finishing
8199260 TQ110LL TQ109YT Electrical installation
8263246 EX135RJ EX129AP Information technology consultancy activities
7815875 TQ126GR TQ110YJ Management consultancy activities other than financial management
6736373 EX176PU EX169WZ Other human health activities
7814267 TQ124PB TQ110YJ Wholesale of other food, including fish, crustaceans and molluscs
1750316 PL206SD PL29BF Architectural activities
8245657 EX311DR EX39AS Other information service activities n.e.c.
4577750 EX392PF EX389AP Sale of used cars and light motor vehicles
1200267 EX171ES EX169WZ Building of pleasure and sporting boats
6411420 EX311TZ EX39AS Technical testing and analysis
7787808 TQ110LL TQ109YT Development of building projects
4092799 EX363LH EX356WY Construction of domestic buildings
8193987 EX392JD EX389AP Advertising agen

9253058 EX202QL EX29ZS Veterinary activities
9115088 TQ126SH TQ110YJ Other information technology service activities
9029259 EX167AE EX159AX Other business support service activities n.e.c.
9121658 EX166QF EX159AX Mixed farming
9384582 TQ122LG TQ110YJ Other human health activities
9196552 EX203QT EX29ZS Data processing, hosting and related activities
9243678 EX392LU EX389AP Other specialised construction activities n.e.c.
9350551 TQ124AA TQ110YJ Renting and leasing of other machinery, equipment and tangible goods n.e.c.
9244342 EX151AE EX149YS Renting and leasing of other machinery, equipment and tangible goods n.e.c.
9183107 EX349LL EX332ZQ Public houses and bars
9146670 EX311DR EX39AS Take-away food shops and mobile food stands
9321638 EX313HX EX39AS Veterinary activities
9380887 TQ148EB TQ139YZ Electrical installation
9279864 EX108LS EX19WN Hairdressing and other beauty treatment
9588795 EX169HU EX159AX Media representation services
9270948 EX151PD EX149YS Other retail sale not in s

9497116 TQ124AA TQ110YJ plied
9430385 TQ126SB TQ110YJ plied
9497293 EX167LE EX159AX plied
9715967 TQ122QA TQ110YJ plied
9734185 EX108JD EX19WN plied
9482905 TQ122LG TQ110YJ plied
9610855 EX347BP EX332ZQ plied
9590715 PL199DN PL189TG plied
9678081 TQ122LG TQ110YJ plied
9977716 PL160HQ PL159ZN plied
9750476 EX393HN EX389AP plied
9959222 TQ124AA TQ110YJ plied
9825020 TQ122QA TQ110YJ plied
9597630 TQ124AA TQ110YJ plied
9943175 TQ122LG TQ110YJ plied
9486787 EX311PJ EX39AS plied
9475803 TQ138JB TQ129TH plied
9918700 EX124AN EX111ZU plied
9728561 EX393HN EX389AP plied
9489855 EX379HP EX369AH plied
9838140 EX393HN EX389AP plied
9921118 EX153PF EX149YS plied
Problem   9835930
9835930  #N/A plied
9809359 EX379SF EX369AH plied
9840766 EX393HN EX389AP plied
9825001 TQ148DA TQ139YZ plied
9673043 EX363LH EX356WY plied
9606801 PL67PP PL68XF plied
9395472 EX141DA EX139AG plied
9736090 TQ148EB TQ139YZ plied
9899331 EX153XZ EX149YS plied
9495577 EX328HR EX314ZQ plied
9827238 PL219SG PL207UZ plied
957131

3870763 EX174NQ EX169WZ Management consultancy activities other than financial management
8943740 EX313AN EX39AS Activities auxiliary to financial intermediation n.e.c.
8356724 EX311TZ EX39AS Other engineering activities
9056527 TQ139AE TQ129TH Other retail sale not in stores, stalls or markets
4551911 EX364BB EX356WY Television programme production activities
7971076 TQ148EB TQ139YZ Information technology consultancy activities
5729982 EX109NN EX19WN Maintenance and repair of motor vehicles
7919125 EX109PZ EX19WN Extraction of crude petroleum
8939475 EX141DA EX139AG Retail sale of beverages in specialised stores
6610585 EX171DJ EX169WZ Educational support services
8135586 EX111XW EX109YN Construction of commercial buildings
6529642 EX391RR EX389AP Other specialised construction activities n.e.c.
7149660 TQ123BQ TQ110YJ Information technology consultancy activities
5295574 EX135RJ EX129AP Manufacture of other furniture
8463424 EX151AE EX149YS Manufacture of other parts and accessories 

8295025 TQ139AE TQ129TH Other retail sale not in stores, stalls or markets
6663222 EX169BW EX159AX Information technology consultancy activities
2471901 TQ124AA TQ110YJ Residents property management
4600134 EX173AH EX169WZ Mixed farming
7373735 EX167DN EX159AX Activities of insurance agents and brokers
8425414 EX204LU EX29ZS Residents property management
4717133 EX328HR EX314ZQ Take-away food shops and mobile food stands
7990538 EX226DY EX215ZG Support activities for crop production
5384591 EX204LB EX29ZS Other professional, scientific and technical activities n.e.c.
7957677 EX151AE EX149YS Information technology consultancy activities
3328319 EX364HP EX356WY Raising of poultry
5705722 EX314SY EX39AS Financial management
4877360 EX153UR EX149YS Raising of other cattle and buffaloes
5729430 PL160BZ PL159ZN Other professional, scientific and technical activities n.e.c.
5089016 TQ130GB TQ129TH Other professional, scientific and technical activities n.e.c.
7724350 EX169AL EX159AX Informati

8062891 TQ126JD TQ110YJ Mixed farming
4830854 EX141PE EX139AG Other information technology service activities
6703660 TQ124AA TQ110YJ Activities of other holding companies n.e.c.
5393496 EX393BA EX389AP Other activities of employment placement agencies
8284577 EX176LA EX169WZ Retail sale of flowers, plants, seeds, fertilizers, pet animals and pet food in specialised stores
1254572 EX311TZ EX39AS Public houses and bars
8809221 EX395RA EX389AP Activities of head offices
708691 PL199JL PL189TG Other letting and operating of own or leased real estate
8551918 EX172AJ EX169WZ Activities of distribution holding companies
4137603 PL190NR PL189TG Retail sale via mail order houses or via Internet
4495941 TQ122QA TQ110YJ Manufacture of other fabricated metal products n.e.c.
7566533 TQ125NE TQ110YJ Other letting and operating of own or leased real estate
8137018 EX164LA EX159AX Buying and selling of own real estate
8554155 EX393DX EX389AP Non-trading company
1139040 EX151BW EX149YS Manufacture of 

5972035 EX122AD EX111ZU Other manufacturing n.e.c.
4403028 EX100PH EX19WN Other holiday and other collective accommodation
8962455 EX311DR EX39AS Landscape service activities
4762803 EX331HA EX329PH Licensed restaurants
8439293 EX135AX EX129AP Hotels and similar accommodation
8413060 TQ122LG TQ110YJ Other letting and operating of own or leased real estate
1908981 EX122AD EX111ZU Other manufacturing n.e.c.
3533381 EX135AD EX129AP Physical well-being activities
8591729 EX135XG EX129AP Activities of open-ended investment companies
4618236 EX141BJ EX139AG Other passenger land transport
5068444 EX311EU EX39AS Accounting and auditing activities
7964609 TQ124AA TQ110YJ Sale of used cars and light motor vehicles
5388691 EX392AA EX389AP Architectural activities
7038598 EX201AS EX29ZS Fitness facilities
6124742 EX394AJ EX389AP Other business support service activities n.e.c.
7189079 TQ123XF TQ110YJ Other business support service activities n.e.c.
8435179 TQ122JS TQ110YJ Raising of dairy cattle
6

395754 TQ122PX TQ110YJ Activities of head offices
7108110 PL219GA PL207UZ Manufacture of fruit and vegetable juice
2132250 TQ149AE TQ139YZ Agents involved in the sale of timber and building materials
497569 EX226TB EX215ZG Other letting and operating of own or leased real estate
4311365 EX198PS EX187YU Wholesale of grain, unmanufactured tobacco, seeds and animal feeds
1131701 TQ137AL TQ129TH Buying and selling of own real estate
7513974 EX122TS EX111ZU Other education n.e.c.
1106198 TQ122JS TQ110YJ Growing of cereals (except rice), leguminous crops and oil seeds
4078224 PL219AE PL207UZ Other specialised construction activities n.e.c.
3449782 TQ149SL TQ139YZ Electrical installation
1685923 TQ122LG TQ110YJ Taxi operation
3138953 EX396DQ EX389AP Management consultancy activities other than financial management
1227271 EX141SG EX139AG Manufacture of pumps
4248120 EX109DN EX19WN Electrical installation
1221612 TQ137UB TQ129TH Raising of other cattle and buffaloes
7319013 EX311EU EX39AS Repa

7266115 EX149QN EX139AG Manufacture of ice cream
7907350 EX111EU EX109YN Private security activities
7213960 EX111LQ EX109YN Other professional, scientific and technical activities n.e.c.
8009305 EX215JD EX209AL Raising of swine/pigs
7083802 EX100HL EX19WN Plastering
764702 EX314EX EX39AS Freshwater aquaculture
4806332 EX166PH EX159AX Agents involved in the sale of machinery, industrial equipment, ships and aircraft
4557824 EX203JD EX29ZS Book publishing
6628934 EX109EX EX19WN First-degree level higher education
5014899 TQ121EF TQ110YJ Development of building projects
1977072 EX176HG EX169WZ Agents involved in the sale of fuels, ores, metals and industrial chemicals
7579386 EX363LH EX356WY Buying and selling of own real estate
5281578 EX363LH EX356WY Development of building projects
3917305 TQ122PT TQ110YJ Accounting and auditing activities
7995343 EX227HU EX215ZG Construction of other civil engineering projects n.e.c.
9016648 EX226HL EX215ZG Retail sale of hardware, paints and glass i

7924251 TQ124AU TQ110YJ Retail trade of motor vehicle parts and accessories
9283332 EX168PT EX159AX Other letting and operating of own or leased real estate
9148639 TQ122HP TQ110YJ Other education n.e.c.
7930864 EX363LH EX356WY Other service activities n.e.c.
8090380 EX141DA EX139AG Specialists medical practice activities
8059643 EX363LH EX356WY Other service activities n.e.c.
5941886 EX108LS EX19WN Residents property management
8180724 TQ126LA TQ110YJ Public houses and bars
8545061 TQ137LH TQ129TH Management consultancy activities other than financial management
6337039 PL74PB PL74PA Other human health activities
2798147 EX153QL EX149YS Residents property management
9306086 EX363LH EX356WY Development of building projects
7678777 TQ122SN TQ110YJ Agents involved in the sale of timber and building materials
4706845 EX331AA EX329PH Museums activities
5029166 EX363LH EX356WY Management of real estate on a fee or contract basis
3531836 EX166PT EX159AX Computer facilities management activit

4527367 EX201QQ EX29ZS Management consultancy activities other than financial management
5108407 TQ124PH TQ110YJ Printing n.e.c.
6506799 EX320AL EX314ZQ Dormant Company
4994857 TQ122JS TQ110YJ Manufacture of other fabricated metal products n.e.c.
5016393 TQ35QG TQ33ZX Other publishing activities
3576260 EX111AF EX109YN Other business support service activities n.e.c.
6182028 EX167AW EX159AX Buying and selling of own real estate
4392707 PL219AE PL207UZ Manufacture of air and spacecraft and related machinery
6838352 EX173LA EX169WZ ther software consultancy and supply
4471710 EX151XQ EX149YS Accounting and auditing activities
2799049 EX202TH EX29ZS Buying and selling of own real estate
4282143 TQ121GJ TQ110YJ Other telecommunications activities
6897962 EX320QA EX314ZQ Hotels and similar accommodation
2534698 PL219AE PL207UZ Wired telecommunications activities
6665839 TQ124AA TQ110YJ Non-trading company
4222488 PL210SG PL207UZ estaurants
3810440 EX141BJ EX139AG Buying and selling of own r

9417734 EX246BU EX239ZX plied
9385409 EX166AA EX159AX Other transportation support activities
6493053 EX187SJ EX179AT Other retail sale not in stores, stalls or markets
4643262 TQ138AP TQ129TH Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials
7143079 TQ137QH TQ129TH Other business support service activities n.e.c.
6464519 EX201UB EX29ZS Retail trade of motor vehicle parts and accessories
5031221 TQ139AD TQ129TH Management consultancy activities other than financial management
9440733 TQ148EB TQ139YZ plied
9435319 EX392AA EX389AP plied
6827861 TQ148EB TQ139YZ Other business support service activities n.e.c.
9428387 PL219QT PL207UZ plied
7131703 EX168RR EX159AX Management consultancy activities other than financial management
7167805 TQ139AE TQ129TH Wholesale of flowers and plants
6819628 EX328HR EX314ZQ Management consultancy activities other than financial management
7372448 EX135RJ EX129AP Other business support service activities n.e

4443441  #N/A Development of building projects
6714697 TQ139AE TQ129TH Retail sale via mail order houses or via Internet
8861723 EX108LS EX19WN Real estate agencies
6836585 EX153DA EX149YS Other amusement and recreation activities n.e.c.
3729409 TQ149AY TQ139YZ Tax consultancy
7399500 TQ148EB TQ139YZ Non-specialised wholesale trade
6327411 TQ148EB TQ139YZ Management consultancy activities other than financial management
Problem   2908967
2908967  #N/A Other letting and operating of own or leased real estate
7328253 TQ124AT TQ110YJ Taxi operation
6077400 PL210UT PL207UZ Fitness facilities
4866291 EX395AA EX389AP Floor and wall covering
3164857 EX173DY EX169WZ Publishing of  consumer and business journals and periodicals
3727438 TQ148EB TQ139YZ Architectural activities
6078250 EX141BJ EX139AG Taxi operation
7484181 PL199DP PL189TG Hairdressing and other beauty treatment
2676287 EX166SR EX159AX Retail sale via mail order houses or via Internet
4762765 EX320EJ EX314ZQ Development of buildi